# Generated by Django 3.2.16 on 2022-11-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterData',
            new_name='SearchData',
        ),
    ]
